#ifndef HEATSHRINK_CONFIG_H
#define HEATSHRINK_CONFIG_H

#ifndef HEATSHRINK_DYNAMIC_ALLOC
#define HEATSHRINK_DYNAMIC_ALLOC 0
#endif

#define HEATSHRINK_STATIC_INPUT_BUFFER_SIZE 32
#define HEATSHRINK_STATIC_WINDOW_BITS 8
#define HEATSHRINK_STATIC_LOOKAHEAD_BITS 4

#define HEATSHRINK_USE_INDEX 1

#endif
